name: 'proof-it'
author: 'Sorin Sbarnea'
description: 'Verify that a PR has right labels before merge.'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
