on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  dogfooding:
    name: dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify PR label action
        uses: ./
        id: proofit
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
